name = "MicroCollections"
uuid = "128add7d-3638-4c79-886c-908ea0c25c34"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.2-DEV"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
BangBang = "0.3.21"
Setfield = "0.4, 0.5, 0.6, 0.7, 0.8"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test"]
